name: Build and Publish Kodi Repository

on:
  push:
    tags:
      - "v*"  # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract version from Git tag
      id: extract_version
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "Extracted version: ${GITHUB_REF#refs/tags/}"
        
    - name: Install zip and hashlib tools
      run: sudo apt-get update && sudo apt-get install -y zip

    - name: Update version in addon.xml
      run: |
        sed -i "s/\(<addon[^>]*version=\)\"[^\"]*\"/\1\"${VERSION}\"/" plugin.video.strmer/addon.xml
        echo "Updated addon.xml with version: ${VERSION}"

    - name: Package Kodi addon
      run: |
        zip -r "plugin.video.strmer-${VERSION}.zip" plugin.video.strmer 

    - name: Generate repository files
      run: |
        mkdir -p repo
        echo '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' > repo/addons.xml
        echo '<addons>' >> repo/addons.xml
        unzip -p "plugin.video.strmer-${VERSION}.zip" plugin.video.strmer/addon.xml | sed '1d' >> repo/addons.xml
        echo '</addons>' >> repo/addons.xml
        md5sum repo/addons.xml | cut -d ' ' -f 1 > repo/addons.xml.md5
        mv "plugin.video.strmer-${VERSION}.zip" repo/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: repo
        publish_branch: gh-pages
